### ISSUE TITLE
Provide HTML tag in the page.

### ISSUE THREAD

**Issue by Yanatg** [Marvel-Universe/MarvelUniverse#82]
Some of the description has the html tag showing up.

![Image 24-11-2566 BE at 20 46](https://github.com/Marvel-Universe/MarvelUniverse/assets/115054563/dc0cb853-95c3-4343-8458-f1cf068c53b9)
![Image 24-11-2566 BE at 20 53](https://github.com/Marvel-Universe/MarvelUniverse/assets/115054563/4d28a728-c524-479a-8cbb-4ca2d3c0a2c2)

**Comment by oatwarat** [comment]
resolved it, already remove unknwon text and other variant text from the context description.
