### ISSUE TITLE
Url route show error.

### ISSUE THREAD

**Issue by Yanatg** [Marvel-Universe/MarvelUniverse#83]
When try to visit the url and access to the character's id (or character's no.) which is not in your app. It show the error page up.

![Image 24-11-2566 BE at 20 49](https://github.com/Marvel-Universe/MarvelUniverse/assets/115054563/c5e125c4-b2e7-4520-ba18-9721c7f13839)

**Comment by oatwarat** [comment]
the bugs have been solved, thanks for your guidance.
