### ISSUE TITLE
I can access the admin page

### ISSUE THREAD

**Issue by 21Gxme** [Marvel-Universe/MarvelUniverse#84]
<img width="1470" alt="image" src="https://github.com/Marvel-Universe/MarvelUniverse/assets/113856957/b32f138c-6a41-407e-8582-72ec73046d59">

[Link](http://marvel-universe-d10a25c19d7d.herokuapp.com/admin/login/?next=/admin/)

**Comment by oatwarat** [comment]
delete the admin path already, so now user wont be able to access this page.
