### ISSUE TITLE
In Data directory, many important datas are provided and README contain admin username/password

### ISSUE THREAD

**Issue by Sosokker** [Marvel-Universe/MarvelUniverse#90]
[google client secret](https://github.com/Marvel-Universe/MarvelUniverse/blob/b172d0bda924400d3c25c3849943011d28408372/data/google-oauth-data.json#L1027C34-L1027C34) 

and 

[admin username, password](https://github.com/Marvel-Universe/MarvelUniverse/blob/b172d0bda924400d3c25c3849943011d28408372/README.md?plain=1#L34)

please delete these data.

**Comment by oatwarat** [comment]
resolved this problem, we already remove the important datas from README including admin's password and username.
